# Logo Url
# Please enter the absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo: https://raw.githubusercontent.com/wanggnim/website/gh-pages/fancybox/title.png

# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  vertx2: http://books.gnim.wang/vertx2/index.html
  vertx3: http://wanggnim.github.io/vertx3/

# Article list grouped by year 
groupByYear: true

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
sidebar: left // sidebar's position (left or right)
social_links:
  github: https://github.com/wanggnim
  weibo:
  rss:
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
fb_admins:
fb_app_id:
